export type ProjectDetail = {
  slug: string
  title: string
  description: string
  longDescription: string
  features: string[]
  stack: string[]
  link: string
  linkLabel: string
  github?: string
}

export const projectDetails: ProjectDetail[] = [
  {
    slug: 'portal-proteger',
    title: 'Portal Proteger',
    description: 'Portal institucional com sistema de gestão de conteúdo. Design profissional focado em acessibilidade e usabilidade.',
    longDescription: 'Portal institucional completo desenvolvido com Next.js e TypeScript. O projeto inclui sistema de gestão de conteúdo (CMS) que permite ao cliente gerenciar páginas, artigos e mídia sem conhecimento técnico. Design responsivo seguindo princípios de acessibilidade WCAG 2.1.',
    features: ['Sistema de gestão de conteúdo (CMS)', 'Design responsivo mobile-first', 'Navegação acessível (WCAG 2.1)', 'SEO otimizado com Next.js SSR/SSG', 'Formulário de contato integrado', 'Hospedagem Cloudflare Pages'],
    stack: ['React', 'TypeScript', 'Next.js', 'Cloudflare'],
    link: 'https://portalproteger.online/',
    linkLabel: 'Ver Site',
  },
  {
    slug: 'portal-eca',
    title: 'Portal ECA',
    description: 'Portal dedicado ao Estatuto da Criança e do Adolescente. Conteúdo educativo, navegação intuitiva e design responsivo.',
    longDescription: 'Portal educacional dedicado ao Estatuto da Criança e do Adolescente (ECA). O site organiza e disponibiliza conteúdo jurídico-educativo de forma acessível, com sistema de busca inteligente e categorização por temas. Desenvolvido com React, TypeScript e Next.js, oferece navegação intuitiva para pais, educadores e profissionais do direito.',
    features: ['Conteúdo educativo sobre o ECA', 'Artigos e materiais de referência', 'Busca otimizada de conteúdo', 'Design responsivo e acessível', 'SEO com Next.js SSR'],
    stack: ['React', 'TypeScript', 'Next.js'],
    link: 'https://portaleca.online/',
    linkLabel: 'Ver Site',
  },
  {
    slug: 'nativa-onstreaming',
    title: 'Nativa OnStreaming',
    description: 'App mobile para a rádio Nativa com streaming ao vivo 24h. Disponível na Google Play e Apple App Store.',
    longDescription: 'Aplicativo mobile oficial da Rádio Nativa OnStreaming com transmissão ao vivo 24 horas. Construído com React Native e TypeScript, o app oferece streaming de áudio de alta qualidade com suporte a background playback — o áudio continua tocando mesmo com o app em segundo plano. Interface intuitiva e moderna, publicada em ambas as lojas oficiais (Google Play e Apple App Store).',
    features: ['Streaming de áudio ao vivo 24h', 'Background playback (áudio em segundo plano)', 'Interface intuitiva e moderna', 'Suporte Android + iOS', 'Notificações push', 'Publicado nas lojas oficiais'],
    stack: ['React Native', 'TypeScript', 'Android', 'iOS', 'Streaming'],
    link: 'https://play.google.com/store/apps/details?id=com.belmontprogramador.radionativaonstreaming&hl=pt',
    linkLabel: 'Ver na Google Play',
    github: 'https://github.com/belmontprogramador/nativaapp',
  },
  {
    slug: 'aromaambient',
    title: 'AromaAmbient',
    description: 'E-commerce de aromatizantes construído com Shopify Liquid. Loja completa com catálogo de produtos, carrinho e checkout.',
    longDescription: 'E-commerce completo de aromatizantes desenvolvido na plataforma Shopify. O projeto envolveu a customização completa do tema usando Liquid, a linguagem de template da Shopify. Inclui páginas de produto otimizadas para conversão, carrinho lateral dinâmico com atualização em tempo real, e integração nativa com o checkout da Shopify. Design limpo e focado em usabilidade para maximizar vendas.',
    features: ['Tema Shopify customizado em Liquid', 'Páginas de produto otimizadas para SEO', 'Carrinho lateral dinâmico', 'Integração com checkout Shopify', 'Design responsivo', 'Catálogo com categorias e filtros'],
    stack: ['Liquid', 'Shopify', 'E-commerce', 'JavaScript'],
    link: 'https://github.com/belmontprogramador/aromaambient',
    github: 'https://github.com/belmontprogramador/aromaambient',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'sitenativaradio',
    title: 'Site Nativa Radio',
    description: 'Website para rádio online com streaming ao vivo, construído com TypeScript e design responsivo.',
    longDescription: 'Website responsivo para a Rádio Nativa OnStreaming com player de streaming integrado. O site oferece programação ao vivo, grade de horários, informações sobre locutores e contato. Construído com foco em performance e experiência do ouvinte, com carregamento rápido e navegação fluida.',
    features: ['Player de streaming integrado', 'Grade de programação', 'Perfis de locutores', 'Design responsivo', 'SEO otimizado'],
    stack: ['TypeScript', 'React', 'Streaming', 'Front-end'],
    link: 'https://github.com/belmontprogramador/sitenativaradio',
    github: 'https://github.com/belmontprogramador/sitenativaradio',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'vertexai',
    title: 'VertexAI',
    description: 'Projeto integrando APIs de inteligência artificial com JavaScript.',
    longDescription: 'Projeto de exploração prática das APIs do Google Vertex AI utilizando JavaScript. Integração com modelos de linguagem para processamento de linguagem natural, incluindo análise de sentimento, classificação de texto e geração de conteúdo. O projeto serve como prova de conceito para integração de IA em aplicações web modernas.',
    features: ['Integração com Google Vertex AI', 'Processamento de linguagem natural', 'Análise de sentimento', 'Classificação de texto', 'Geração de conteúdo'],
    stack: ['JavaScript', 'Google Vertex AI', 'API REST', 'AI/ML'],
    link: 'https://github.com/belmontprogramador/vertexai',
    github: 'https://github.com/belmontprogramador/vertexai',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'lummensite',
    title: 'LummenSite',
    description: 'Site institucional moderno com React. Layout profissional, animações suaves e formulário de contato integrado.',
    longDescription: 'Site institucional do ecossistema Lummen, construído com React e TypeScript. Design moderno com animações CSS suaves, seções bem estruturadas para apresentação de serviços e portfólio. Inclui formulário de contato com validação e integração com EmailJS para envio de mensagens diretamente ao cliente.',
    features: ['Design moderno com animações', 'Seções institucionais completas', 'Formulário de contato funcional', 'Totalmente responsivo', 'Performance otimizada'],
    stack: ['React', 'TypeScript', 'Front-end', 'EmailJS'],
    link: 'https://github.com/belmontprogramador/lummensite',
    github: 'https://github.com/belmontprogramador/lummensite',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'crud-simples-users',
    title: 'CRUD Simples Users',
    description: 'API de gerenciamento de usuários com Node.js, Express, Prisma ORM e autenticação JWT.',
    longDescription: 'API RESTful completa para gerenciamento de usuários, construída com Node.js e Express. Utiliza Prisma ORM para modelagem e migrações de banco de dados, autenticação via JWT com access e refresh tokens, e validação de dados com Zod. Projeto ideal como base para sistemas que precisam de cadastro, login e controle de acesso com segurança robusta.',
    features: ['CRUD completo de usuários', 'Registro com hash de senha (bcrypt)', 'Login com JWT (access + refresh tokens)', 'Middleware de autenticação', 'Validação de dados com Zod', 'Migrations com Prisma', 'Arquitetura limpa e modular'],
    stack: ['Node.js', 'Express', 'Prisma', 'PostgreSQL', 'JWT', 'Zod'],
    link: 'https://github.com/belmontprogramador/crud-simples-users',
    github: 'https://github.com/belmontprogramador/crud-simples-users',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'app-lummen',
    title: 'App Lummen',
    description: 'Aplicativo mobile do ecossistema Lummen. Interface moderna com React Native e TypeScript.',
    longDescription: 'Aplicativo mobile nativo do ecossistema Lummen, desenvolvido com React Native e TypeScript. Oferece experiência mobile completa para os usuários da plataforma, com navegação intuitiva, integração com APIs do ecossistema Lummen e design consistente com a identidade visual da marca.',
    features: ['Interface mobile nativa', 'Integração com backend Lummen', 'Navegação intuitiva', 'Design consistente com a marca', 'Performance otimizada'],
    stack: ['React Native', 'TypeScript', 'Mobile'],
    link: 'https://github.com/belmontprogramador/app-lummen',
    github: 'https://github.com/belmontprogramador/app-lummen',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'backend-lummen',
    title: 'Backend Lummen',
    description: 'API backend do ecossistema Lummen com JavaScript, Express e banco de dados relacional.',
    longDescription: 'API backend que serve como núcleo do ecossistema Lummen. Construída com JavaScript e Express, fornece endpoints RESTful para autenticação, gestão de conteúdo e integração entre os diversos módulos da plataforma (site, app mobile e painel admin). Estrutura modular com controllers, services e middleware organizados por domínio.',
    features: ['API RESTful completa', 'Autenticação e autorização', 'Estrutura modular por domínio', 'Validação de dados', 'Integração com banco relacional'],
    stack: ['JavaScript', 'Express', 'API REST', 'Back-end'],
    link: 'https://github.com/belmontprogramador/backend-lummen',
    github: 'https://github.com/belmontprogramador/backend-lummen',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'painel-lummen',
    title: 'Painel Admin Lummen',
    description: 'Painel administrativo com TypeScript para gestão de conteúdo, blogs e usuários do ecossistema Lummen.',
    longDescription: 'Painel administrativo central do ecossistema Lummen. Dashboard completo para gestão de conteúdo do site e blog, gerenciamento de usuários e configurações da plataforma. Construído com TypeScript, oferece interface limpa e produtiva para administradores gerenciarem todos os aspectos do ecossistema.',
    features: ['Dashboard administrativo', 'Gestão de conteúdo do site', 'Gerenciamento de blog', 'Controle de usuários', 'Configurações da plataforma'],
    stack: ['TypeScript', 'Dashboard', 'Admin', 'Front-end'],
    link: 'https://github.com/belmontprogramador/painel-lummen',
    github: 'https://github.com/belmontprogramador/painel-lummen',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'jobs',
    title: 'Plataforma de Vagas',
    description: 'Plataforma web de empregos com TypeScript e React. Busca inteligente, filtros avançados e sistema de candidaturas.',
    longDescription: 'Plataforma web completa para busca e candidatura a vagas de emprego. Construída com TypeScript e React, oferece interface moderna com busca inteligente por palavras-chave, filtros avançados por localização, senioridade e tipo de contrato, e sistema completo de candidatura com formulário integrado. Dados mockados em JSON prontos para integração com API real.',
    features: ['Busca inteligente de vagas', 'Filtros avançados (localização, senioridade, tipo)', 'Detalhes completos da vaga', 'Formulário de candidatura', 'Design responsivo', 'Dados prontos para integração com API'],
    stack: ['TypeScript', 'React', 'Plataforma Web', 'Front-end'],
    link: 'https://github.com/belmontprogramador/jobs',
    github: 'https://github.com/belmontprogramador/jobs',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'checkout',
    title: 'Sistema de Checkout',
    description: 'Sistema de checkout completo com TypeScript. Carrinho, cálculo de frete, pagamento e finalização de compra.',
    longDescription: 'Sistema de checkout completo construído com TypeScript. Implementa todo o fluxo de finalização de compra: carrinho dinâmico com atualização em tempo real, cálculo de frete por CEP, resumo do pedido, múltiplas opções de pagamento, validação de formulários e tela de confirmação. Componentizado e pronto para integração com gateways de pagamento.',
    features: ['Carrinho de compras dinâmico', 'Cálculo de frete por CEP', 'Resumo do pedido em tempo real', 'Múltiplas formas de pagamento', 'Validação de formulários', 'Fluxo completo até confirmação'],
    stack: ['TypeScript', 'Checkout', 'E-commerce', 'Front-end'],
    link: 'https://github.com/belmontprogramador/checkout',
    github: 'https://github.com/belmontprogramador/checkout',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'folha-ponto',
    title: 'Folha de Ponto Digital',
    description: 'Sistema completo de registro de ponto eletrônico com front-end React e API back-end em JavaScript.',
    longDescription: 'Sistema completo de ponto eletrônico digital composto por front-end React e API back-end em JavaScript. Permite registro de batidas (entrada, saída, almoço), dashboard com cálculo automático de horas trabalhadas e extras, relatórios mensais exportáveis e autenticação segura de funcionários. Arquitetura cliente-servidor com API RESTful.',
    features: ['Registro de ponto (entrada/saída/almoço)', 'Dashboard com horas trabalhadas', 'Relatórios mensais exportáveis', 'Autenticação de funcionários', 'Cálculo automático de horas extras', 'Arquitetura cliente-servidor'],
    stack: ['JavaScript', 'React', 'Node.js', 'API REST', 'Ponto Eletrônico'],
    link: 'https://github.com/belmontprogramador/front-folha-ponto',
    github: 'https://github.com/belmontprogramador/front-folha-ponto',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'prefeitura-araruama',
    title: 'Site Prefeitura de Araruama',
    description: 'Portal web institucional para prefeitura municipal. Design responsivo, notícias e serviços ao cidadão.',
    longDescription: 'Portal institucional desenvolvido para prefeitura municipal. Site completo com página inicial de notícias, seção de serviços ao cidadão organizada por categorias, calendário de eventos municipais, área de transparência com publicações oficiais e design responsivo acessível em todos os dispositivos.',
    features: ['Página inicial com notícias e destaques', 'Seção de serviços municipais', 'Calendário de eventos', 'Área de transparência', 'Design responsivo e acessível'],
    stack: ['JavaScript', 'Portal Institucional', 'Front-end'],
    link: 'https://github.com/belmontprogramador/prefeituradeararuama',
    github: 'https://github.com/belmontprogramador/prefeituradeararuama',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'api-email',
    title: 'API de Email',
    description: 'API de envio de emails transacionais com TypeScript e Node.js. Templates HTML, anexos e fila de processamento.',
    longDescription: 'API de envio de emails transacionais construída com TypeScript e Node.js. Suporte completo a templates HTML dinâmicos com variáveis, anexos de arquivos, fila de processamento assíncrono para alta disponibilidade, logs detalhados de entrega e falha, e autenticação via token para segurança dos endpoints.',
    features: ['Envio de emails transacionais', 'Templates HTML dinâmicos', 'Suporte a anexos', 'Fila de processamento assíncrono', 'Logs de entrega e falhas', 'Autenticação por token'],
    stack: ['TypeScript', 'Node.js', 'Email', 'API REST', 'Back-end'],
    link: 'https://github.com/belmontprogramador/api-de-email',
    github: 'https://github.com/belmontprogramador/api-de-email',
    linkLabel: 'Ver no GitHub',
  },
  {
    slug: 'api-sinais',
    title: 'API Sinais Recebidos',
    description: 'API para recebimento e processamento de sinais em tempo real com JavaScript e Node.js.',
    longDescription: 'API especializada em recebimento de webhooks e processamento de sinais em tempo real. Construída com JavaScript e Node.js, implementa validação rigorosa de payload, processamento assíncrono para não bloquear o webhook, persistência em banco de dados e mecanismo de retry automático em caso de falhas no processamento.',
    features: ['Webhook para recebimento de sinais', 'Processamento assíncrono', 'Validação de payload', 'Persistência em banco de dados', 'Retry automático em falhas'],
    stack: ['JavaScript', 'Node.js', 'API', 'Real-time', 'Webhook'],
    link: 'https://github.com/belmontprogramador/api-sinais-recebidos',
    github: 'https://github.com/belmontprogramador/api-sinais-recebidos',
    linkLabel: 'Ver no GitHub',
  },
]
